#!/bin/bash
# Created on 23/11/2018
IFS=$'\n\t'
trap ctrl_c 2
function ctrl_c() {
                echo
                printf "$R [!]-> Joing me on https://t.me/Ivam3_Bot$W
                \n"
}
#Colors
	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'

function Banner {
		echo $(clear)
        printf "$C"
        	echo "            -{> Youtube-dl <} "
        	echo "   -{ SO > Android - Andrax && Termux } "
        	echo "             -{ Adapted by } "
        	printf "$G"
        	echo "      =============================="
        	echo "      .___.                 ______,"
        	echo "      |   |__ ______   ___  \_____ \ "
        	echo "      |   \ \/ /\__ \ /   \   _(__ <,"
        	echo "      |   |\   / __ \| Y Y \ /      \ "
        	echo "      |___| \_/ (____|__|_| /______ /"
        	echo "                     \/    \/      \/ "
        	echo "      ====== By ___ Cinderella ======"
	printf "$C\n"
        	echo "          [---] Join me on [---]"
        	echo "[-] www.youtube.com/c/ivam3bycinderella [-]"
		echo "      [-] t.me/Ivam3byCinderella [-]"
        	echo "            [-] t.me/ivam3 [-]"
	printf "$R\n"
		echo "          [---] README.md [---]"
	printf "$W"
        	echo " This file will install youtube-dl command"
        	echo "     and repositories needed to run it"
       		echo "         Youtube-dl was coded by"
	printf "$G"
		echo "             *Gabi Tiplea*"
	printf "$R\n"
		echo "          [---] DISCLAIMER [---]"
	printf "$W"
        	echo "   If the law is violated with it's use"
        	echo "     This would be the responsibility"
        	echo "        of the user who handled it"
	printf "$R"
		echo "       [-] Use At Your Own Risk [-]"
	printf "$W\n"
	printf "$C         Press$G ENTER$C to continue"
	printf "$W\n"
	read enter
}
function Termux {
	dpkg --configure -a
	apt update && apt -y upgrade -y
	termux-setup-storage
		if [ -d $PREFIX/lib/python3.7/site-packages/youtube_dl ]; then
			yes | pip uninstall youtube_dl
		fi
	printf "$G[!]-> INSTALLING YOUTUBE-DL BY GABI TIPLEA$W\n"
	sleep 1
	apt install -y util-linux wget curl python python-dev python2
	yes | python -m pip install youtube-dl
	mkdir -p $HOME/.config/youtube-dl
	ln -s $PREFIX/bin $HOME/bin
	curl https://raw.githubusercontent.com/ivam3/youtube-dl/master/.data/.netrc -o $HOME/.netrc
	chmod 711 $HOME/.netrc
	curl https://raw.githubusercontent.com/ivam3/youtube-dl/master/.data/LhDxGbtY -o $PREFIX/bin/termux-url-opener
	dos2unix $PREFIX/bin/termux-url-opener
	chmod 711 $PREFIX/bin/termux-url-opener
	rm -rf ../youtube-dl
	printf "\n \n"
	thanks
	chao-chao
}
function Andrax {
        if [ -d $PREFIX/lib/python3.7/site-packages/youtube_dl ]; then
                yes | python3 -m pip uninstall youtube_dl
	fi
        printf "\n \n"
        printf "$G INSTALLING YOUTUBE-DL BY GABI TIPLEA
	$W\n"
        sleep 1
        yes | python3 -m pip install youtube-dl
        if [ ! -d ~/youtube-dl ]; then
		rm -rf ~/youtube-dl
	fi
        printf "\n \n"
        thanks
        chao-chao
}
function thanks {
	printf "$C"
	echo "#-----THANKS TO MY MASTER CINDERELLA-----#"
       	echo "#                                        #"
       	echo "#             People don't die           #"
       	echo "#    If they still live in the hearts    #"
       	echo "#           of their loved ones          #"
       	echo "#       We love her ... We miss her      #"
       	echo "#                                        #"
       	echo "#-------------------RIP------------------#"
       	printf "$W\n"
}
function chao-chao {
	printf "$Y Now you can download any video and mp3 using :
	\n"
	printf ":-->$W $ youtube-dl + url$Y"
	printf ":-->$W $ youtube-dl -u <youremail@email.com> -p <your password> + url$Y\n\n"
	printf "For more details going to community feedback group on Telegram \n\t\t$B >> t.me/Ivam3_Bot$W\n\n"
}	

Banner
DISTRO=$(echo $HOME | grep -oE '([tadermunx]{6,6})')
if [ $DISTRO=termux ]; then Termux
elif [ $DISTRO=andrax ]; then Andrax
else
	echo $(clear)
	printf "$R O.ops unknown distro \n\n"
	thanks
fi

#				@IbyC
